# Generated by Django 4.0.3 on 2022-06-12 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_employee_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='office',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated',
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dispatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.dispatch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.ManyToManyField(related_name='employee', to='training.office'),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
